export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_SIGN_PENDING = 'REQUEST_SIGN_PENDING';
export const REQUEST_SIGN_SUCCESS = 'REQUEST_SIGN_SUCCESS';
export const REQUEST_SIGN_FAILED = 'REQUEST_SIGN_FAILED';
